### ISSUE TITLE
Change compute rest api start/stop to put/delete?

### ISSUE THREAD

**Issue by stevenvanrossem** [sonata-nfv/son-emu#134]
wouldn't it make more sense to use PUT and DELETE http requests (from a REST api -viewpoint)
instead of a different GET for compute start and stop?

**Comment by mpeuster** [comment]
@hadik3r can be closed, right?
https://github.com/sonata-nfv/son-emu/commit/20f1625455289701aa6b90a1043bb29c3d9a9cdd
