### ISSUE TITLE
dummy gatekeeper vnf naming

### ISSUE THREAD

**Issue by stevenvanrossem** [sonata-nfv/son-emu#148]
The dummy GK now assigns its own names to the deplpoyed VNFs in the service: vnf%d
After deployment, there is no way to link the vnf id in the nsd to the actual deployed docker container name?
This would be needed eg. in case the user wants to monitor a vnf  after deployment, only the id in the nsd is known to the user, not the actual name of the deployed container...

Would it be possible to use the vnf id in the nsd as the name for the deployed container?
or is this related to the mininet host name issue: [https://github.com/sonata-nfv/son-emu/issues/2]  ?

As a workaround the dummy GK could return via its rest api the mapping of the nsd vnf id to the real container instance.

Which option would work best you think?

**Comment by stevenvanrossem** [comment]
seems to work to use a long vnf_id as docker name (vnf_id includes underscore and len = 11)
in my test the nsd id is 'ubuntu_vnf1'  and the dummy GK deploys it as 'mn.ubuntu_vnf1'

**Comment by stevenvanrossem** [comment]
see pull request: https://github.com/sonata-nfv/son-emu/pull/149

**Comment by mpeuster** [comment]
Ah. Didn't see this issue ... I have already replied to the commit.

Does the network setup in the mn.ubuntu_vnf1 example still work? E.g. can you ping between the VNFs?

**Comment by stevenvanrossem** [comment]
yes ping works, haven't seen any errors yet...

**Comment by mpeuster** [comment]
Ah cool.

**Comment by mpeuster** [comment]
I can confirm that long VNF ids as container names seem to work with the dummy gatekeeper. I used something like this in my test NSD: "empty_vnf3_with_a_very_long_name" and it worked. I think the issue was more about the length of the interface names as such which are not allowed to have arbitrary long names.
