### ISSUE TITLE
dummy GK mgmt network

### ISSUE THREAD

**Issue by stevenvanrossem** [sonata-nfv/son-emu#150]
The dummy GK should not deploy mgmt networks/connection points from the vnfd.
The default connection to docker0 in the emulator can be considered as the mgmt network.

**Comment by stevenvanrossem** [comment]
see pull request https://github.com/sonata-nfv/son-emu/pull/149

**Comment by mpeuster** [comment]
Sure? What happens if a software/script inside the VNF container expects a interface named mgmt?

**Comment by stevenvanrossem** [comment]
but the mgmt is an E-LAN connection, which is currently not handled  by the dummy GK,
so the mgmt interface will not work, it seemed an unnecessary inerface...
but ok I agree, in case the 'mgmt' name is expected, it should be there, as described in the vnfd.

**Comment by stevenvanrossem** [comment]
closed by https://github.com/sonata-nfv/son-emu/pull/151/commits/8d7557c11dca16cca0edaf77d90b276d1b90e434

**Comment by mpeuster** [comment]
Thats true it is not supported yet. But I guess to support E-LAN connections as well in one of our next versions. Should be possible to install SDN rules to connect all ports of a E-LAN to have a simple HUB-like behaviour or not? What do you think?

**Comment by stevenvanrossem** [comment]
I guess a simple HUB-like behviour means a flowrule that incoming packets are sent out all the ports of the E-LAN.
Idea to implement once we need E-LANs...

**Comment by stevenvanrossem** [comment]
Actually implemented a first shot at an E-LAN network in the dummygatekeeper:
https://github.com/sonata-nfv/son-emu/pull/156/commits/fb6e43a57b60fdfcd643b60c5e53b6df1e65348b
It relies on the learning switch capabilities of the SDN switch in the emulator, so no specific chaining is installed for E-LAN interfaces. They are just connected to the emulator switches.

**Comment by mpeuster** [comment]
@stevenvanrossem Great! I would assume this behavior should be fine for all current E-LAN cases we might have in the demo/example services, or not?
