### ISSUE TITLE
start extra monitoring containers (cAdvisor, Prometheus Pushgateway)

### ISSUE THREAD

**Issue by stevenvanrossem** [sonata-nfv/son-emu#161]
To enable son-monitor to get metrics from the son-emu, cAdvisor and Prometheus' Pushgateway are used.
It makes more sense to start these containers together with son-emu, so they are running in the same environment (eg. inside the same VM). The ports used by cAdvisor(8080) and PushGateway(9091) should be mapped correctly.
Starting this monitoring framework is done from the topology file with the 'monitor' option: 
DCNetwork( monitor=True)

**Comment by mpeuster** [comment]
I already added the ports to the Vagrant file: https://github.com/sonata-nfv/son-emu/pull/162

We have to check how to start the additional containers within the VM.

**Comment by stevenvanrossem** [comment]
cadvisor and pushgateway are started by son-emu, by using a flag in :
net = DCNetwork( monitor=True,...)
see commit https://github.com/sonata-nfv/son-emu/commit/0e1c20dd64c363dd7af0af2d3157a0d5be664762
