### ISSUE TITLE
Y1 demo does not work if the enable_learning flag of the topology is set

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-emu#175]
- I couldn't identify the reason for this behavior yet.
- It looks like that the chain rules are not used when learning switch is enabled even though they should have a higher priority.

For the demo we don't need this functionality so we should postpone the fix to end of this month.

**Comment by stevenvanrossem** [comment]
One thing I noticed is that there is a traffic loop created when: 
- learning is enabled
- E-LAN (mgmt) network is defined in the NSD
- E-LAN connected VNFs are distributed over multiple dc network switches 

When sniffing with Wireshark, a lot of packets get re-flooded infinitely, they are broadcast packets sent over the E-LAN and flooded to every interface of all the VNFs.
This can cause the emulator switches or fw_vnf to overload and not properly forward the pcap traffic any more.

A more isolated implementation of E-LAN is needed. Taking into account it should enable correct forwarding of broadcast packets (only on the E-LAN) and that an E-LAN can be distributed over multiple DC switches.

**Comment by mpeuster** [comment]
@stevenvanrossem that seems to be the reason for it. I fully agree that we need a more isolated E-LAN implementation. This should be one of the features for the next release 👍
