### ISSUE TITLE
son-monitor: update monitor REST API

### ISSUE THREAD

**Issue by stevenvanrossem** [sonata-nfv/son-emu#189]
include {vnf_interface}, {metric}, {cookie} in the JSON data, iso in the URL:
/monitor/{vnf_name} /{vnf_interface} /{metric}/{cookie}

it is more simple and easier to extend when only using 1 URL for the monitoring REST API:
/monitor/{vnf_name}

**Comment by mpeuster** [comment]
This is done, right?

**Comment by stevenvanrossem** [comment]
The monitor REST API is now structured like this:
/restapi/monitor/interface/<vnf_name>/<vnf_interface>/<metric>/<cookie>
/restapi/monitor/flow/<vnf_name>/<vnf_interface>/<metric>/<cookie>
/restapi/monitor/link/<vnf_src_name>/<vnf_dst_name>

I still need to implement it differently in Flask in son-emu:
all parameters <vnf_name>, <vnf_interface>,... should be included as parameter in the url:
e.g. /restapi/monitor/interface?vnf_name=value1&vnf_interface=value2&...
I learned that Flask can easily do this, this also seems more REST-compliant and easier to document

**Comment by stevenvanrossem** [comment]
this is done. e89e5e4349de0012666cd5be59d4d047193e8465
I started a wiki page to keep track of the current REST api status:  [REST api](https://github.com/sonata-nfv/son-emu/wiki/REST-API-command-overview)
