### ISSUE TITLE
Re-align dummy GK APIs with new son-cli tools (son-access)

### ISSUE THREAD

**Issue by mpeuster** [sonata-nfv/son-emu#195]
Should not be too much effort.

Should be started after `son-access` is finalized.

**Comment by stevenvanrossem** [comment]
I just noticed son-push is not any more included in the install of son-cli, the source code folder has also been romved from the repo,
so any integration test that uses son-push will fail now :-(

**Comment by mpeuster** [comment]
Exactly. I am only aware of the int-6-emu... test so far. Will modify it to use son-access this morning.
