### ISSUE TITLE
Question: does this support distributed deployment across hosts?

### ISSUE THREAD

**Issue by yogeshVU** [sonata-nfv/son-emu#215]
mininet can run only on one host. Maxinet can run across hosts.
does this support distributed deployment across hosts?

**Comment by mpeuster** [comment]
Hi @yogeshVU, you are right about Maxinet. However, son-emu does currently not support the deployment across multiple physical hosts. 

If you need this, you should rely on a bare Maxinet (+ maybe + Containernet) installation without the son-emu features.

http://maxinet.github.io
