### ISSUE TITLE
NAT with two interfaces (not working)

### ISSUE THREAD

**Issue by knodir** [sonata-nfv/son-emu#232]
Hi,

Can you please take a look at [this](https://gist.github.com/knodir/711413e359dbed49f9b294244ed63e63) example and point out what I am doing wrong? 

I am trying to do network address translation between two interfaces, each on different subnet. Topology is `client <-> nat <-> server`, where `nat`'s `input` interface is facing the `client` and `output` interface is facing the `server` VNF. `client` VNF can ping `input` interface of the `nat` (and vice-versa), and `server` can ping `output` interface of the `nat` VNF (and vice-versa).

I see ARP requests coming on `nat`'s `input` when I do `containernet> client ping -c 2 server`, as follows:

```
root@nat:/# tcpdump -ne -i any host 10.0.10.10                                                                        
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes
18:25:14.360956   B 92:52:a6:4b:75:b8 ethertype ARP (0x0806), length 44: Request who-has 10.0.10.10 tell 10.0.0.2, length 28
18:25:15.360947   B 92:52:a6:4b:75:b8 ethertype ARP (0x0806), length 44: Request who-has 10.0.10.10 tell 10.0.0.2, length 28
```

But ping fails with `Destination Host Unreachable` as follows:
```
containernet> client ping -c 2 server
PING 10.0.10.10 (10.0.10.10) 56(84) bytes of data.
From 10.0.0.2 icmp_seq=1 Destination Host Unreachable
From 10.0.0.2 icmp_seq=2 Destination Host Unreachable

--- 10.0.10.10 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1005ms
```

I feel that I am missing something simple, but could not figure it out after 6 hours :( 

Any help is appreciated.

**Comment by FRuffy** [comment]
```
We were able to fix the problem by running
echo 1 > /proc/sys/net/ipv4/ip_forward
echo 1 > /proc/sys/net/ipv4/conf/all/proxy_arpiptables -t nat -A POSTROUTING -o output -j MASQUERADE
iptables -A FORWARD -i output -o input -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -A FORWARD -i input -o output -j ACCEPT
```
on the nat host. The problem was that arp packets were being dropped on the input interface and forwarding was not configured properly.

**Comment by knodir** [comment]
Thanks @FRuffy!
