### ISSUE TITLE
Can VNF interface be added/removed in runtime?

### ISSUE THREAD

**Issue by knodir** [sonata-nfv/son-emu#236]
Once we create the vnf as follows (see example [here](https://github.com/sonata-nfv/son-emu/blob/fa0e0b54bd172a621eff71be6352e88a69b8d29f/src/emuvim/test/unittests/test_emulator.py#L140))

```
vnf1 = self.dc[0].startCompute("vnf1", network=[{'id':'intf1', 'ip':'10.0.10.1/24'}])
```

can we add one more interface to the vnf such that it will look like this?
```
vnf1 = self.dc[0].startCompute("vnf1", network=[{'id':'intf1', 'ip':'10.0.10.1/24'},
                                                {'id':'intf1', 'ip':'10.0.11.1/24'}])
```

Or should all VNF interfaces be created before calling `startCompute()`? 

I came across [`addLink()`](https://github.com/sonata-nfv/son-emu/blob/87b6b3511d63824479313b259d84b581377927a6/src/emuvim/dcemulator/node.py#L279) function in the repo, but that seems to be just for connecting "existing" VNF interface to the switch, which is not what I want.

**Comment by mpeuster** [comment]
Hi,

I guess `addLink()` might do the job, because it will create a new interface inside the container!

I don't have its detailed signature in mind right now but something like this should work:

```python

vnf1 = self.dc[0].startCompute("vnf1" ... )

# add second interface
self.net.addLink(
    vnf1,  # VNF object
    s1,  # VNF or switch to connect to
    intfName1="intf0",  # name of vnf1 interface
    params1={"ip": "20.0.0.1/24"},  # ip of vnf1 interface
    #intfName2="s1-eth0", # not needed for switch (use defaults)
    #params2={"ip": "20.0.0.2/24"},  # not needed for switch
    cls=Link)

# add third interface
self.net.addLink(
    vnf1,  # VNF object
    s2,  # VNF or switch to connect to
    intfName1="intf1",  # name of vnf1 interface
    params1={"ip": "30.0.0.1/24"},  # ip of vnf1 interface
    cls=Link)
```

Does this help? Adding an interface only (without link) is not directly supported.
(Does not mean that there is no hack to achieve it, but I never needed or tried it)
